export const authConstants = {
  SESSION_CREATE_REQUEST: 'SESSION_CREATE_REQUEST',
  SESSION_CREATE_SUCCESS: 'SESSION_CREATE_SUCCESS',
  SESSION_CREATE_FAILURE: 'SESSION_CREATE_FAILURE',

  SESSION_DELETE_REQUEST: 'SESSION_DELETE_REQUEST',
  SESSION_DELETE_SUCCESS: 'SESSION_DELETE_SUCCESS',
  SESSION_DELETE_FAILURE: 'SESSION_DELETE_FAILURE',
  
  SESSION_RESTORE_REQUEST: 'SESSION_RESTORE_REQUEST',
  SESSION_RESTORE_SUCCESS: 'SESSION_RESTORE_SUCCESS',
  SESSION_RESTORE_FAILURE: 'SESSION_RESTORE_FAILURE'
};
